[package]
name = "llmsh-llm-openai"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
llmsh-llm = { path = "../llmsh-llm" }

[dev-dependencies]
wiremock = "0.6"
tokio = { workspace = true }
